<?php

namespace ContainerJUa5M60;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupeTagService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ReoWKSP.App\Entity\GroupeTag' shared service.
     *
     * @return \App\Entity\GroupeTag
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ReoWKSP": it references class "App\\Entity\\GroupeTag" but no such service exists.');
    }
}
