<?php

namespace Container7Vzo9BF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RzvmP4XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RzvmP4X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RzvmP4X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CompetenceController::ArchiveGroupCompetence' => ['privates', '.service_locator.wBA8aWt', 'get_ServiceLocator_WBA8aWtService', true],
            'App\\Controller\\CompetenceController::DesarchiveCompetence' => ['privates', '.service_locator.IZ8CcC4', 'get_ServiceLocator_IZ8CcC4Service', true],
            'App\\Controller\\CompetenceController::DesarchiveGroupCompetence' => ['privates', '.service_locator.wBA8aWt', 'get_ServiceLocator_WBA8aWtService', true],
            'App\\Controller\\CompetenceController::__invoke' => ['privates', '.service_locator.IZ8CcC4', 'get_ServiceLocator_IZ8CcC4Service', true],
            'App\\Controller\\CompetenceController::addCompetence' => ['privates', '.service_locator.o19tePx', 'get_ServiceLocator_O19tePxService', true],
            'App\\Controller\\CompetenceController::index' => ['privates', '.service_locator.m9AEmXY', 'get_ServiceLocator_M9AEmXYService', true],
            'App\\Controller\\CompetenceController::indexGroup' => ['privates', '.service_locator.0quEBrZ', 'get_ServiceLocator_0quEBrZService', true],
            'App\\Controller\\CompetenceController::removeCompetence' => ['privates', '.service_locator.o19tePx', 'get_ServiceLocator_O19tePxService', true],
            'App\\Controller\\GroupeTagController::addTag' => ['privates', '.service_locator.pZQoo.Z', 'get_ServiceLocator_PZQoo_ZService', true],
            'App\\Controller\\GroupeTagController::index' => ['privates', '.service_locator.V029P5N', 'get_ServiceLocator_V029P5NService', true],
            'App\\Controller\\GroupeTagController::removeTag' => ['privates', '.service_locator.ReoWKSP', 'get_ServiceLocator_ReoWKSPService', true],
            'App\\Controller\\ProfilController::__invoke' => ['privates', '.service_locator.Fl4EBh8', 'get_ServiceLocator_Fl4EBh8Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\TagController::index' => ['privates', '.service_locator..h8.8vE', 'get_ServiceLocator__H8_8vEService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\CompetenceController:ArchiveGroupCompetence' => ['privates', '.service_locator.wBA8aWt', 'get_ServiceLocator_WBA8aWtService', true],
            'App\\Controller\\CompetenceController:DesarchiveCompetence' => ['privates', '.service_locator.IZ8CcC4', 'get_ServiceLocator_IZ8CcC4Service', true],
            'App\\Controller\\CompetenceController:DesarchiveGroupCompetence' => ['privates', '.service_locator.wBA8aWt', 'get_ServiceLocator_WBA8aWtService', true],
            'App\\Controller\\CompetenceController:__invoke' => ['privates', '.service_locator.IZ8CcC4', 'get_ServiceLocator_IZ8CcC4Service', true],
            'App\\Controller\\CompetenceController' => ['privates', '.service_locator.IZ8CcC4', 'get_ServiceLocator_IZ8CcC4Service', true],
            'App\\Controller\\CompetenceController:addCompetence' => ['privates', '.service_locator.o19tePx', 'get_ServiceLocator_O19tePxService', true],
            'App\\Controller\\CompetenceController:index' => ['privates', '.service_locator.m9AEmXY', 'get_ServiceLocator_M9AEmXYService', true],
            'App\\Controller\\CompetenceController:indexGroup' => ['privates', '.service_locator.0quEBrZ', 'get_ServiceLocator_0quEBrZService', true],
            'App\\Controller\\CompetenceController:removeCompetence' => ['privates', '.service_locator.o19tePx', 'get_ServiceLocator_O19tePxService', true],
            'App\\Controller\\GroupeTagController:addTag' => ['privates', '.service_locator.pZQoo.Z', 'get_ServiceLocator_PZQoo_ZService', true],
            'App\\Controller\\GroupeTagController:index' => ['privates', '.service_locator.V029P5N', 'get_ServiceLocator_V029P5NService', true],
            'App\\Controller\\GroupeTagController:removeTag' => ['privates', '.service_locator.ReoWKSP', 'get_ServiceLocator_ReoWKSPService', true],
            'App\\Controller\\ProfilController:__invoke' => ['privates', '.service_locator.Fl4EBh8', 'get_ServiceLocator_Fl4EBh8Service', true],
            'App\\Controller\\ProfilController' => ['privates', '.service_locator.Fl4EBh8', 'get_ServiceLocator_Fl4EBh8Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\TagController:index' => ['privates', '.service_locator..h8.8vE', 'get_ServiceLocator__H8_8vEService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\CompetenceController::ArchiveGroupCompetence' => '?',
            'App\\Controller\\CompetenceController::DesarchiveCompetence' => '?',
            'App\\Controller\\CompetenceController::DesarchiveGroupCompetence' => '?',
            'App\\Controller\\CompetenceController::__invoke' => '?',
            'App\\Controller\\CompetenceController::addCompetence' => '?',
            'App\\Controller\\CompetenceController::index' => '?',
            'App\\Controller\\CompetenceController::indexGroup' => '?',
            'App\\Controller\\CompetenceController::removeCompetence' => '?',
            'App\\Controller\\GroupeTagController::addTag' => '?',
            'App\\Controller\\GroupeTagController::index' => '?',
            'App\\Controller\\GroupeTagController::removeTag' => '?',
            'App\\Controller\\ProfilController::__invoke' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TagController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CompetenceController:ArchiveGroupCompetence' => '?',
            'App\\Controller\\CompetenceController:DesarchiveCompetence' => '?',
            'App\\Controller\\CompetenceController:DesarchiveGroupCompetence' => '?',
            'App\\Controller\\CompetenceController:__invoke' => '?',
            'App\\Controller\\CompetenceController' => '?',
            'App\\Controller\\CompetenceController:addCompetence' => '?',
            'App\\Controller\\CompetenceController:index' => '?',
            'App\\Controller\\CompetenceController:indexGroup' => '?',
            'App\\Controller\\CompetenceController:removeCompetence' => '?',
            'App\\Controller\\GroupeTagController:addTag' => '?',
            'App\\Controller\\GroupeTagController:index' => '?',
            'App\\Controller\\GroupeTagController:removeTag' => '?',
            'App\\Controller\\ProfilController:__invoke' => '?',
            'App\\Controller\\ProfilController' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TagController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
