<?php

namespace ContainerXeTkgj0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QREGncrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qREGncr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qREGncr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formateurRepo' => ['privates', 'App\\Repository\\FormateurRepository', 'getFormateurRepositoryService', true],
        ], [
            'formateurRepo' => 'App\\Repository\\FormateurRepository',
        ]);
    }
}
