<?php

namespace ContainerXeTkgj0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormateurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QyYeJQT.App\Entity\Formateur' shared service.
     *
     * @return \App\Entity\Formateur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.QyYeJQT": it references class "App\\Entity\\Formateur" but no such service exists.');
    }
}
