<?php

namespace ContainerXeTkgj0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupCompetenceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.o19tePx.App\Entity\GroupCompetence' shared service.
     *
     * @return \App\Entity\GroupCompetence
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.o19tePx": it references class "App\\Entity\\GroupCompetence" but no such service exists.');
    }
}
