<?php

namespace ContainerS87Iql3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F4frAhDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F4frAhD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F4frAhD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\PromoRepository', 'getPromoRepositoryService', true],
            'repoPDS' => ['privates', 'App\\Repository\\ProfilSortieRepository', 'getProfilSortieRepositoryService', true],
            'serialize' => ['services', 'serializer', 'getSerializerService', false],
        ], [
            'repo' => 'App\\Repository\\PromoRepository',
            'repoPDS' => 'App\\Repository\\ProfilSortieRepository',
            'serialize' => '?',
        ]);
    }
}
