<?php

namespace ContainerRZUwtbS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Re0hHMJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Re0hHMJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Re0hHMJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'referentiel' => ['privates', '.errored..service_locator.Re0hHMJ.App\\Entity\\Referentiel', NULL, 'Cannot autowire service ".service_locator.Re0hHMJ": it references class "App\\Entity\\Referentiel" but no such service exists.'],
            'repo' => ['privates', 'App\\Repository\\CompetenceRepository', 'getCompetenceRepositoryService', true],
        ], [
            'referentiel' => 'App\\Entity\\Referentiel',
            'repo' => 'App\\Repository\\CompetenceRepository',
        ]);
    }
}
