<?php

namespace ContainerRZUwtbS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6ImjCoxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6ImjCox' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6ImjCox'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repoApprenant' => ['privates', 'App\\Repository\\ApprenantRepository', 'getApprenantRepositoryService', true],
            'repoCompetence' => ['privates', 'App\\Repository\\CompetenceRepository', 'getCompetenceRepositoryService', true],
            'repoComptVal' => ['privates', 'App\\Repository\\CompetencesValidesRepository', 'getCompetencesValidesRepositoryService', true],
            'repoPromo' => ['privates', 'App\\Repository\\PromoRepository', 'getPromoRepositoryService', true],
            'repoReferentiel' => ['privates', 'App\\Repository\\ReferentielRepository', 'getReferentielRepositoryService', true],
        ], [
            'repoApprenant' => 'App\\Repository\\ApprenantRepository',
            'repoCompetence' => 'App\\Repository\\CompetenceRepository',
            'repoComptVal' => 'App\\Repository\\CompetencesValidesRepository',
            'repoPromo' => 'App\\Repository\\PromoRepository',
            'repoReferentiel' => 'App\\Repository\\ReferentielRepository',
        ]);
    }
}
