<?php

namespace ContainerRZUwtbS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApprenantLivrablePartielControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ApprenantLivrablePartielController' shared autowired service.
     *
     * @return \App\Controller\ApprenantLivrablePartielController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
        include_once \dirname(__DIR__, 4).'\\src\\Controller\\ApprenantLivrablePartielController.php';

        $container->services['App\\Controller\\ApprenantLivrablePartielController'] = $instance = new \App\Controller\ApprenantLivrablePartielController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\BriefRepository'] ?? $container->load('getBriefRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\ApprenantLivrablePartielController', $container));

        return $instance;
    }
}
