<?php

namespace ContainerPHGuKuQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BfKi3x6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bfKi3x6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bfKi3x6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'briefRepo' => ['privates', 'App\\Repository\\BriefRepository', 'getBriefRepositoryService', true],
            'groupeRepo' => ['privates', 'App\\Repository\\GroupPromoRepository', 'getGroupPromoRepositoryService', true],
            'promoRepo' => ['privates', 'App\\Repository\\PromoRepository', 'getPromoRepositoryService', true],
        ], [
            'briefRepo' => 'App\\Repository\\BriefRepository',
            'groupeRepo' => 'App\\Repository\\GroupPromoRepository',
            'promoRepo' => 'App\\Repository\\PromoRepository',
        ]);
    }
}
