<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Brief extends \App\Entity\Brief implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'langue', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'nomBrief', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'contexte', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'modalitePedagogique', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'modaliteEvaluation', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'critereEvaluation', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'imagePromo', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'archive', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'etat_brouillon_assigne_valide', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'createAt', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'etatBriefGroup', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'briefMaPromo', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'formateur', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'tags', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'livrableAttendus', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'ressources', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'niveaux', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'livrablePartiels'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'langue', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'nomBrief', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'contexte', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'modalitePedagogique', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'modaliteEvaluation', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'critereEvaluation', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'imagePromo', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'archive', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'etat_brouillon_assigne_valide', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'createAt', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'etatBriefGroup', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'briefMaPromo', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'formateur', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'tags', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'livrableAttendus', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'ressources', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'niveaux', '' . "\0" . 'App\\Entity\\Brief' . "\0" . 'livrablePartiels'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Brief $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLangue(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLangue', []);

        return parent::getLangue();
    }

    /**
     * {@inheritDoc}
     */
    public function setLangue(string $langue): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLangue', [$langue]);

        return parent::setLangue($langue);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomBrief(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomBrief', []);

        return parent::getNomBrief();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomBrief(string $nomBrief): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomBrief', [$nomBrief]);

        return parent::setNomBrief($nomBrief);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getContexte(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContexte', []);

        return parent::getContexte();
    }

    /**
     * {@inheritDoc}
     */
    public function setContexte(string $contexte): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContexte', [$contexte]);

        return parent::setContexte($contexte);
    }

    /**
     * {@inheritDoc}
     */
    public function getModalitePedagogique(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModalitePedagogique', []);

        return parent::getModalitePedagogique();
    }

    /**
     * {@inheritDoc}
     */
    public function setModalitePedagogique(string $modalitePedagogique): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModalitePedagogique', [$modalitePedagogique]);

        return parent::setModalitePedagogique($modalitePedagogique);
    }

    /**
     * {@inheritDoc}
     */
    public function getModaliteEvaluation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModaliteEvaluation', []);

        return parent::getModaliteEvaluation();
    }

    /**
     * {@inheritDoc}
     */
    public function setModaliteEvaluation(string $modaliteEvaluation): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModaliteEvaluation', [$modaliteEvaluation]);

        return parent::setModaliteEvaluation($modaliteEvaluation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCritereEvaluation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCritereEvaluation', []);

        return parent::getCritereEvaluation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCritereEvaluation(string $critereEvaluation): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCritereEvaluation', [$critereEvaluation]);

        return parent::setCritereEvaluation($critereEvaluation);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagePromo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagePromo', []);

        return parent::getImagePromo();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagePromo($imagePromo): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagePromo', [$imagePromo]);

        return parent::setImagePromo($imagePromo);
    }

    /**
     * {@inheritDoc}
     */
    public function getArchive(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchive', []);

        return parent::getArchive();
    }

    /**
     * {@inheritDoc}
     */
    public function setArchive(bool $archive): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArchive', [$archive]);

        return parent::setArchive($archive);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatBrouillonAssigneValide(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatBrouillonAssigneValide', []);

        return parent::getEtatBrouillonAssigneValide();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatBrouillonAssigneValide(string $etat_brouillon_assigne_valide): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatBrouillonAssigneValide', [$etat_brouillon_assigne_valide]);

        return parent::setEtatBrouillonAssigneValide($etat_brouillon_assigne_valide);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateAt', []);

        return parent::getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateAt(\DateTimeInterface $createAt): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateAt', [$createAt]);

        return parent::setCreateAt($createAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatBriefGroup(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatBriefGroup', []);

        return parent::getEtatBriefGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function addEtatBriefGroup(\App\Entity\EtatBriefGroupe $etatBriefGroup): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEtatBriefGroup', [$etatBriefGroup]);

        return parent::addEtatBriefGroup($etatBriefGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEtatBriefGroup(\App\Entity\EtatBriefGroupe $etatBriefGroup): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEtatBriefGroup', [$etatBriefGroup]);

        return parent::removeEtatBriefGroup($etatBriefGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getBriefMaPromo(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBriefMaPromo', []);

        return parent::getBriefMaPromo();
    }

    /**
     * {@inheritDoc}
     */
    public function addBriefMaPromo(\App\Entity\BriefMaPromo $briefMaPromo): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBriefMaPromo', [$briefMaPromo]);

        return parent::addBriefMaPromo($briefMaPromo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBriefMaPromo(\App\Entity\BriefMaPromo $briefMaPromo): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBriefMaPromo', [$briefMaPromo]);

        return parent::removeBriefMaPromo($briefMaPromo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormateur(): ?\App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormateur', []);

        return parent::getFormateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormateur(?\App\Entity\Utilisateur $formateur): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormateur', [$formateur]);

        return parent::setFormateur($formateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getTags(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', []);

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function addTag(\App\Entity\Tag $tag): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTag', [$tag]);

        return parent::addTag($tag);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTag(\App\Entity\Tag $tag): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTag', [$tag]);

        return parent::removeTag($tag);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivrableAttendus(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivrableAttendus', []);

        return parent::getLivrableAttendus();
    }

    /**
     * {@inheritDoc}
     */
    public function addLivrableAttendu(\App\Entity\LivrableAttendu $livrableAttendu): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLivrableAttendu', [$livrableAttendu]);

        return parent::addLivrableAttendu($livrableAttendu);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLivrableAttendu(\App\Entity\LivrableAttendu $livrableAttendu): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLivrableAttendu', [$livrableAttendu]);

        return parent::removeLivrableAttendu($livrableAttendu);
    }

    /**
     * {@inheritDoc}
     */
    public function getRessources(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRessources', []);

        return parent::getRessources();
    }

    /**
     * {@inheritDoc}
     */
    public function addRessource(\App\Entity\Ressource $ressource): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRessource', [$ressource]);

        return parent::addRessource($ressource);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRessource(\App\Entity\Ressource $ressource): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRessource', [$ressource]);

        return parent::removeRessource($ressource);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveaux(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveaux', []);

        return parent::getNiveaux();
    }

    /**
     * {@inheritDoc}
     */
    public function addNiveau(\App\Entity\Niveau $niveau): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNiveau', [$niveau]);

        return parent::addNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNiveau(\App\Entity\Niveau $niveau): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNiveau', [$niveau]);

        return parent::removeNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivrablePartiels(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivrablePartiels', []);

        return parent::getLivrablePartiels();
    }

    /**
     * {@inheritDoc}
     */
    public function addLivrablePartiel(\App\Entity\LivrablePartiel $livrablePartiel): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLivrablePartiel', [$livrablePartiel]);

        return parent::addLivrablePartiel($livrablePartiel);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLivrablePartiel(\App\Entity\LivrablePartiel $livrablePartiel): \App\Entity\Brief
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLivrablePartiel', [$livrablePartiel]);

        return parent::removeLivrablePartiel($livrablePartiel);
    }

}
