<?php

namespace ContainerNgMXSzy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F4LG53SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F4LG53S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F4LG53S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'promo' => ['privates', '.errored..service_locator.F4LG53S.App\\Entity\\Promo', NULL, 'Cannot autowire service ".service_locator.F4LG53S": it references class "App\\Entity\\Promo" but no such service exists.'],
            'repoApplivrablePartiel' => ['privates', 'App\\Repository\\ApprenantLivrablePartielRepository', 'getApprenantLivrablePartielRepositoryService', true],
            'repoApprenant' => ['privates', 'App\\Repository\\ApprenantRepository', 'getApprenantRepositoryService', true],
            'repoCompetence' => ['privates', 'App\\Repository\\CompetenceRepository', 'getCompetenceRepositoryService', true],
            'repoComptVal' => ['privates', 'App\\Repository\\CompetencesValidesRepository', 'getCompetencesValidesRepositoryService', true],
            'repoNiveaux' => ['privates', 'App\\Repository\\NiveauRepository', 'getNiveauRepositoryService', true],
        ], [
            'promo' => 'App\\Entity\\Promo',
            'repoApplivrablePartiel' => 'App\\Repository\\ApprenantLivrablePartielRepository',
            'repoApprenant' => 'App\\Repository\\ApprenantRepository',
            'repoCompetence' => 'App\\Repository\\CompetenceRepository',
            'repoComptVal' => 'App\\Repository\\CompetencesValidesRepository',
            'repoNiveaux' => 'App\\Repository\\NiveauRepository',
        ]);
    }
}
