<?php

namespace ContainerNgMXSzy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.F4LG53S.App\Entity\Promo' shared service.
     *
     * @return \App\Entity\Promo
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.F4LG53S": it references class "App\\Entity\\Promo" but no such service exists.');
    }
}
