<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZGPxu85\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZGPxu85/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZGPxu85.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZGPxu85\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZGPxu85\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZGPxu85',
    'container.build_id' => 'cc648d53',
    'container.build_time' => 1599486993,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZGPxu85');
