<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZCxZg1Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZCxZg1Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZCxZg1Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZCxZg1Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZCxZg1Y\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZCxZg1Y',
    'container.build_id' => '7639da39',
    'container.build_time' => 1595507881,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZCxZg1Y');
