<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7Vzo9BF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7Vzo9BF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7Vzo9BF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7Vzo9BF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7Vzo9BF\App_KernelDevDebugContainer([
    'container.build_hash' => '7Vzo9BF',
    'container.build_id' => '91e03117',
    'container.build_time' => 1597648222,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7Vzo9BF');
