<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerY5EmAzf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY5EmAzf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY5EmAzf.legacy');
=======
if (\class_exists(\ContainerXeTkgj0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXeTkgj0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXeTkgj0.legacy');
>>>>>>> 132ec3dacb62e772b2dfa7eb7de6404d040248a5

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerY5EmAzf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY5EmAzf\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y5EmAzf',
    'container.build_id' => '115327b0',
    'container.build_time' => 1598364387,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY5EmAzf');
=======
    \class_alias(\ContainerXeTkgj0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXeTkgj0\App_KernelDevDebugContainer([
    'container.build_hash' => 'XeTkgj0',
    'container.build_id' => '290cbc83',
    'container.build_time' => 1598363048,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXeTkgj0');
>>>>>>> 132ec3dacb62e772b2dfa7eb7de6404d040248a5
