<?php

namespace ContainerNgMXSzy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfilService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Fl4EBh8.App\Entity\Profil' shared service.
     *
     * @return \App\Entity\Profil
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Fl4EBh8": it references class "App\\Entity\\Profil" but no such service exists.');
    }
}
