<?php

namespace ContainerNgMXSzy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReferentiel2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.atvCle0.App\Entity\Referentiel' shared service.
     *
     * @return \App\Entity\Referentiel
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.atvCle0": it references class "App\\Entity\\Referentiel" but no such service exists.');
    }
}
